### ISSUE TITLE
Set keybinding to include. key

### ISSUE THREAD

**Issue by dannyfritz** [Maestroschan/emoji-selector-for-gnome#50]
How would I set the keybinding to `<Super>.`? This is the keybinding Windows 10 uses for the emoji keyboard.

**Comment by Maestroschan** [comment]
https://github.com/GNOME/gtk/blob/master/gdk/keynames.txt maybe it's `period` ?

**Comment by dannyfritz** [comment]
`<super>period` works. Thanks :+1:

**Comment by nnnnicholas** [comment]
Humble suggestion: allow using `.` as an alias of `period`. Couldn't for the life of me figure out why it wasn't working

**Comment by maoschanz** [comment]
almost none of the gdk keynames are intuitive, and it wouldn't be reasonable to alias the keyboard management from a widely known gnome core lib because you "couldn't figure out" how to click the link next to the text input

gtk4's version of the inputs to set keyboard shortcuts by typing them is simpler to support than the gtk3 one, i'll use that instead when i'll have gnome 3.40 or 3.41

**Comment by nnnnicholas** [comment]
Five people in Github issues with the same question.. maybe the link next to the text input is the problem, not the user. No need to be snide. Glad to hear more recent GTK makes this easier. Thank you for continuing to write this software.

**Comment by maoschanz** [comment]
the other users opened their issues (50 53 and 128) before i added this link (september 2020, in issue 128), or between the moment i added it and the moment i released it (130), and it's more calm since then, so i think the link (while not being the optimal solution) has done a pretty good job
